/*
* Generated file
*
* Generated from: yang module name: tapapp-impl yang module local name: tapapp-impl
* Generated by: org.opendaylight.controller.config.yangjmxgenerator.plugin.JMXGenerator
* Generated at: Tue Jan 31 04:34:45 PST 2017
*
* Do not modify this file unless it is present under src/main directory
*/
package org.sdnhub.odl.tutorial.tapapp.impl;
public interface TutorialTapAppModuleMXBean {
    public javax.management.ObjectName getRpcRegistry();

    public void setRpcRegistry(javax.management.ObjectName rpcRegistry);

    public javax.management.ObjectName getDataBroker();

    public void setDataBroker(javax.management.ObjectName dataBroker);

    public javax.management.ObjectName getNotificationService();

    public void setNotificationService(javax.management.ObjectName notificationService);

}
